### ISSUE TITLE
openrave rosmake failure

### ISSUE THREAD

**Issue by gxxzs** [rpapallas/openrave#1]
i want to install UR5 OpenRAVE Controller, so i follow the tips to install openrave. But when i ran rosmake.Mistakes happens.:

zs@zs:~/rosmake_ws/openrave$ rosmake
[ rosmake ] rosmake starting...                                                 
[ rosmake ] No package selected and the current directory is not the correct path for package 'openrave'.
[ rosmake ] Packages requested are: []                                          
[ rosmake ] Logging to directory /home/zs/.ros/rosmake/rosmake_output-20181207-034831
[ rosmake ] Expanded args [] to:
[]                                             
[ rosmake ] ERROR: No arguments could be parsed into valid package or stack names.
zs@zs:~/rosmake_ws/openrave$ rosmake
[ rosmake ] rosmake starting...                                                 
[ rosmake ] No package selected and the current directory is not the correct path for package 'openrave'.
[ rosmake ] Packages requested are: []                                          
[ rosmake ] Logging to directory /home/zs/.ros/rosmake/rosmake_output-20181207-035419
[ rosmake ] Expanded args [] to:
[]                                             
[ rosmake ] ERROR: No arguments could be parsed into valid package or stack names.
 
Did this files intact? Thanks!

**Comment by rpapallas** [comment]
Hi @gxxzs,

Please note that the UR5 Controller is now converted to a **catkin** package. As such, this repository (i.e., `openrave`) is not any more valid for building the `ur5controller`.

Please create a catkin workspace by following [this](http://wiki.ros.org/catkin/Tutorials/create_a_workspace) tutorial. Then follow the instructions of the [ur5controller](https://github.com/roboticsleeds/ur5controller) to clone and build ur5controller as a catkin package instead. You will also need the `openrave_catkin` package from [here](https://github.com/personalrobotics/openrave_catkin). All the details are available [here](https://github.com/roboticsleeds/ur5controller#dependencies).
